### ISSUE TITLE
I encountered an error when executing: ${directory,,}: bad substitution

### ISSUE THREAD

**Issue by smokeriu** [alitokmen/maven-repository-cleaner#1]
My operating system is `macOS`.

I tried `zsh` and `bash`, and both prompted this error. I'm not too familiar with the shell, and it involves deleting files. That's why I'd like to consult you before I actually execute it.

- MacOS version: `13.6.7 (22G720)`
- Bash version: `GNU bash, version 3.2.57(1)-release (x86_64-apple-darwin22)`

**Comment by alitokmen** [comment]
Sadly, bash 3.2 is actually over 15 years old and doesn't support character substitution (and has [over 10 year old security vulnerabilities that can be used to distribute malware](https://en.wikipedia.org/wiki/Shellshock_(software_bug))). Apple tend to take their time to upgrade certain components, and there is little one can do to influence their decisions.

I would recommend you follow one of the many great blogs on the Internet to upgrade the bash version on your macOS, so this script (and many other modern bash scripts) is usable on your machine. As an added bonus, upgrading bash would reduce your Apple system's exposure to well known security vulnerabilities.

**Comment by alitokmen** [comment]
And, I recognise upgrading macOS components can be a pain sometimes.

I checked in https://github.com/alitokmen/maven-repository-cleaner/commit/bac96ed19d67764e9a56cb8114df1fc7ef357f88 which would make the script compatible with bash 3.x, could you give a try?

**Comment by smokeriu** [comment]
> And, I recognise upgrading macOS components can be a pain sometimes.
> 
> I checked in [bac96ed](https://github.com/alitokmen/maven-repository-cleaner/commit/bac96ed19d67764e9a56cb8114df1fc7ef357f88) which would make the script compatible with bash 3.x, could you give a try?

I tried it. It works fine! Thank you very much.
